### PR TITLE
Content

### PR DESCRIPTION
**Pull request by Adyune**
Made the content box with social icons and scrolling textbox. Awaiting animated svg to add to the header of the component.

### CODE REVIEW

**Review by nategaulke — CHANGES_REQUESTED** [review]
I think the class name should be changed to the name of the file or vice versa. I would assume the same would be true for the folder as well. Also eventually, the images will need to be changed to buttons. Content box might be too big, but other than that it looks good!

**Comment by Adyune** [comment]
> I think the class name should be changed to the name of the file or vice versa. I would assume the same would be true for the folder as well. Also eventually, the images will need to be changed to buttons. Content box might be too big, but other than that it looks good!

I fixed the issues in your stated in your message.

**Review by nategaulke — APPROVED** [review]
New Content Box looks good to me, great job on making those changes so quickly!

**Review by mbruckert — CHANGES_REQUESTED** [review]
Good work! The only issue I noticed is that the social icons are appearing outside of the content box and if I put a lot of content inside the box the content does scroll but it also appears outside the box. Let me know if you need help solving this.

CleanShot 2022-09-29 at 12 30 38@2x

**Comment by Adyune** [comment]
> Good work! The only issue I noticed is that the social icons are appearing outside of the content box and if I put a lot of content inside the box the content does scroll but it also appears outside the box. Let me know if you need help solving this.
> 
> CleanShot 2022-09-29 at 12 30 38@2x

I believe that I fixed the issues that you brought up. Please check them when you have the time.

**Pull request merged**
