### PR TITLE
Create Register Button Component

### PR DESCRIPTION
**Pull request by mbruckert**
I currently have some CSS in this PR because I couldn't figure out how to do some of these things in Tailwind, but in a future release hopefully this will be converted to Tailwind completely.

### CODE REVIEW

**Review by spie51 — APPROVED** [review]
Looks good!

**Review by nategaulke — APPROVED** [review]
Code looks good and when you were modeling at the meeting, looked great!

**Review by nategaulke — CHANGES_REQUESTED** [review]
I was looking at it again, I noticed that when I hovered over the sign, the lettering looked a little strange, attached an image image

**Comment by nategaulke** [comment]
Not sure if that can be fixed or not, but thought I would point it out in case it looked different on your end

**Comment by mbruckert** [comment]
> I was looking at it again, I noticed that when I hovered over the sign, the lettering looked a little strange, attached an image image

Left a question in the Discord channel related to this when you get a chance

**Pull request merged**
