### PR TITLE
Create sidebar component

### PR DESCRIPTION
**Pull request by nategaulke**

### CODE REVIEW

**Comment by nategaulke** [comment]
Future things that could be implemented

    Better transition for backdrop
    transition from "hamburger" to "x" and vice versa
    transition when text goes back to normal size

**Comment by nategaulke** [comment]
(Also the correct fonts)

**Comment by spie51** [comment]
It might be something on my end but whenever I load up the site I just get a blank white screen. Can you send me your App.js file on discord to make sure I'm doing the same thing you are?

**Comment by mbruckert** [comment]
Where are you putting the Sidebar component in your code? Just trying to see if I can replicate your preview.

**Pull request closed without merging**
